# Info feed for actuator's info endpoint
info:
  application:
    name: "@project.artifactId@"
    organization: "@project.groupId@"
    version: "@project.version@"
    description: "@project.description@"
    build-timestamp: "@maven.build.timestamp@"
  dependencies:
    spring-framework: "@spring-framework.version@"
    lombok: "@lombok.version@"
    mapstruct: "@mapstruct.version@"
    commons-lang: "@commons-lang3.version@"
    commons-text: "@commons-text.version@"
    java-jwt: "@java-jwt.version@"
    logback-classic: "@logback-classic.version@"
    logback-json-classic: "@logback-json-classic.version@"
    logback-jackson: "@logback-jackson.version@"
    logstash-logback-encoder: "@logstash-logback-encoder.version@"
    springdoc-openapi-ui: "@springdoc-openapi-ui.version@"
    micrometer-registry-prometheus: "@micrometer.version@"

management:
  endpoint:
    # Provides additional info in response for actuator's health endpoint
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  # Actuator endpoints to enable
  endpoints:
    web:
      exposure:
        include: caches,health,info,loggers,metrics,prometheus,scheduledtasks

# Need this flag for exception handler to receive and process 404 errors
spring:
  mvc:
    throw-exception-if-no-handler-found: true

  # TODO - Move this to default profile
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false