info:
  application:
    name: "@project.artifactId@"
    organization: "@project.groupId@"
    version: "@project.version@"
    description: "@project.description@"
    build-timestamp: "@maven.build.timestamp@"
  dependencies:
    lombok: "@lombok.version@"
    mapstruct: "@mapstruct.version@"
    springdoc-openapi-ui: "@springdoc-openapi-ui.version@"

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: caches,health,info,loggers,metrics,prometheus,scheduledtasks